### ISSUE TITLE
Add to cart breaks when product is in a disabled category

### ISSUE THREAD

**Issue by peterjaap** [yireo/Yireo_GoogleTagManager2#154]
We have products that are in a disabled category (and that disabled category is also in a different root category but I'm not sure that matters). When adding it to the cart, we get this error;

```
==> var/log/system.log <==                                                                                                                   
[2023-06-05T14:55:22.732116+00:00] .CRITICAL: Magento\Framework\Exception\NoSuchEntityException: Geen dergelijke entiteit met id = 1042 in /data/web/releases/20230605102310/vendor/magento/framework/Exception/NoSuchEntityException.php:50
Stack trace:                                                                                                                                 
#0 /data/web/releases/20230605102310/vendor/magento/module-catalog/Model/CategoryRepository.php(159): Magento\Framework\Exception\NoSuchEntityException::singleField()
#1 /data/web/releases/20230605102310/vendor/magento/module-catalog/Model/CategoryList.php(85): Magento\Catalog\Model\CategoryRepository->get()
#2 /data/web/releases/20230605102310/vendor/yireo/magento2-googletagmanager2/Util/GetCategoryFromProduct.php(70): Magento\Catalog\Model\CategoryList->getList()
#3 /data/web/releases/20230605102310/vendor/yireo/magento2-googletagmanager2/DataLayer/Mapper/ProductDataMapper.php(107): Yireo\GoogleTagManager2\Util\GetCategoryFromProduct->getAll()
#4 /data/web/releases/20230605102310/vendor/yireo/magento2-googletagmanager2/DataLayer/Mapper/ProductDataMapper.php(81): Yireo\GoogleTagManager2\DataLayer\Mapper\ProductDataMapper->attachCategoriesData()
#5 /data/web/releases/20230605102310/vendor/yireo/magento2-googletagmanager2/DataLayer/Tag/Product/CurrentProduct.php(35): Yireo\GoogleTagManager2\DataLayer\Mapper\ProductDataMapper->mapByProduct()
#6 /data/web/releases/20230605102310/vendor/yireo/magento2-googletagmanager2/view/frontend/templates/product/details.phtml(19): Yireo\GoogleTagManager2\DataLayer\Tag\Product\CurrentProduct->merge()
#7 /data/web/releases/20230605102310/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')                         
#8 /data/web/releases/20230605102310/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#9 /data/web/releases/20230605102310/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#10 /data/web/releases/20230605102310/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#11 /data/web/releases/20230605102310/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#12 /data/web/releases/20230605102310/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#13 /data/web/releases/20230605102310/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#14 /data/web/releases/20230605102310/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#15 /data/web/releases/20230605102310/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#16 /data/web/releases/20230605102310/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#17 /data/web/releases/20230605102310/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()                                                                                                                                               
#18 /data/web/releases/20230605102310/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()                                                                                                                                                        
#19 /data/web/releases/20230605102310/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()                                                                                                                                              
#20 /data/web/releases/20230605102310/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()                                                                                                                                                       
#21 /data/web/releases/20230605102310/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()  
#22 /data/web/releases/20230605102310/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()                                                                                                                                              
#23 /data/web/releases/20230605102310/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout->renderElement()               
#24 /data/web/releases/20230605102310/vendor/magento/module-catalog/view/frontend/templates/product/view/form.phtml(29): Magento\Framework\View\Element\AbstractBlock->getChildHtml()       
#25 /data/web/releases/20230605102310/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')                                                                  
```

This looks like it breaks adding to the cart, but it actually breaks showing the cart with items in it (at least, on Luma).

We have now temporarily worked around this by changing [line 70](https://github.com/yireo/Yireo_GoogleTagManager2/blob/3.2.3/Util/GetCategoryFromProduct.php#L70) to:

```
try {
        return $this->categoryListRepository->getList($searchCriteria)->getItems();
} catch (\Exception $e) {
    return [];
}
```

However, this will return NO categories at all when at least ONE of them is disabled. So it's not a perfect workaround.

**Comment by jissereitsma** [comment]
I've now added a simple check to filter the categories of the product by `is_active`. Release 3.2.4 includes this. This seems to be working for the regular functionality. Does this fix things for you?

**Comment by jellesiderius** [comment]
We're getting the same issue here, but then on category pages.

**Comment by jissereitsma** [comment]
Strange. I was unable to duplicate this in my environments (2.3.7, 2.4.7, PHP 8.1, PHP 8.2): Grabbing a product, disabling its categories, adding the product to the cart, no issue. Which Magento versions were you using?

Anyway, I added another fix under 3.2.5. Could you see if this solved it for me? If not, I really first need to find a way to replicate the issue myself.

**Comment by jellesiderius** [comment]
@jissereitsma, if you want to, you can test and try on a staging environment. You can contact me through Discord or Slack if you want to.

**Comment by jissereitsma** [comment]
@peterjaap  I just did, and it still works as expected. 
@jellesiderius Perhaps ...

To make sure this doesn't bug too much, I have added the workaround that PJ described (catching the exception) because either way, with whatever fix, this should not cause an exception in the live environment. Next, there is now a better fix for selecting the right categories. Could you try out release 3.2.6?

Note that you shouldn't try to check for an exception (well, you should, but that exception should be gone), but you should debug the Data Layer to make sure all desired categories are in the `item` props as well.
