### ISSUE TITLE
JS Error after click on product in catalog page Magento2 "Uncaught ReferenceError: YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS is not defined"

### ISSUE THREAD

**Issue by oksana-serhiienko** [yireo/Yireo_GoogleTagManager2#175]
The issue was found on catalog page Magento2. If you click on the product - you get the error
Uncaught ReferenceError: YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS is not defined
    at HTMLAnchorElement.<anonymous> (clicks.min.js:1:220)
    at HTMLAnchorElement.dispatch (jquery.min.js:348:476)
    at elemData.handle (jquery.min.js:334:166)

The problem was in vendor/yireo/magento2-googletagmanager2/view/frontend/web/js/product/clicks.js  file
 in row const debugClicks = YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS || false;

The fix for this is to change the row into
 const debugClicks = window['YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS'] || false;

**Comment by jissereitsma** [comment]
Thanks for addressing this issue. I've applied your fix in the place you mentioned but actually also another place. Release 3.5.1 is now shipping with this fix.
